# -*- coding: utf-8 -*-
"""Deep Learning Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQOhD7dlQ1UWD93vJjJRa06hz_cEKlsE

# ==========================================================
# Handwritten Digit Recognition using CNN (MNIST) with PyTorch
# ==========================================================
#
# Project Type:
# Deep Learning Project using CNN and PyTorch
#
# Objective:
# Build and train a Convolutional Neural Network (CNN)
# to classify handwritten digits (0–9) using the MNIST dataset.
#
# ==========================================================

# Import Required Libraries
"""

import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms

from torch.utils.data import DataLoader
from torch.utils.data import random_split

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

"""# Device Configuration"""

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using Device:", device)

"""# Data Preprocessing and Transformations
# Load MNIST Dataset
"""

# ==========================================================
# Data Preprocessing and Transformations
# ==========================================================

transform = transforms.Compose([
    transforms.ToTensor(),

    # Normalize MNIST dataset
    transforms.Normalize((0.5,), (0.5,))
])

# ==========================================================
# Load MNIST Dataset
# ==========================================================

train_dataset = torchvision.datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

test_dataset = torchvision.datasets.MNIST(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

print("Training Dataset Size:", len(train_dataset))
print("Testing Dataset Size:", len(test_dataset))

"""# Split Training Dataset into:
# Training Set and Validation Set
"""

train_size = int(0.8 * len(train_dataset))
val_size = len(train_dataset) - train_size

train_data, val_data = random_split(
    train_dataset,
    [train_size, val_size]
)

print("Training Set Size:", len(train_data))
print("Validation Set Size:", len(val_data))

"""#Visualize Sample Images"""

# Display Sample Images


plt.figure(figsize=(10,5))

for i in range(10):

    image, label = train_dataset[i]

    plt.subplot(2,5,i+1)

    plt.imshow(image.squeeze(), cmap='gray')

    plt.title(f"Label: {label}")

    plt.axis('off')

plt.tight_layout()
plt.show()

"""Build CNN Model"""

# ==========================================================
# CNN Model Definition
# ==========================================================

class CNNModel(nn.Module):

    def __init__(self):

        super(CNNModel, self).__init__()

        # First Convolutional Layer
        self.conv1 = nn.Conv2d(
            in_channels=1,
            out_channels=32,
            kernel_size=3,
            padding=1
        )

        # Second Convolutional Layer
        self.conv2 = nn.Conv2d(
            in_channels=32,
            out_channels=64,
            kernel_size=3,
            padding=1
        )

        # Max Pooling Layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # Dropout Layer
        self.dropout = nn.Dropout(0.5)

        # Fully Connected Layers
        self.fc1 = nn.Linear(64 * 7 * 7, 128)

        self.fc2 = nn.Linear(128, 10)

        # ReLU Activation
        self.relu = nn.ReLU()

    def forward(self, x):

        # First Convolution Block
        x = self.conv1(x)
        x = self.relu(x)
        x = self.pool(x)

        # Second Convolution Block
        x = self.conv2(x)
        x = self.relu(x)
        x = self.pool(x)

        # Flatten
        x = x.view(x.size(0), -1)

        # Fully Connected Layer
        x = self.fc1(x)
        x = self.relu(x)

        # Dropout
        x = self.dropout(x)

        # Output Layer
        x = self.fc2(x)

        return x

"""Model Summary"""

# ==========================================================
# Initialize Model
# ==========================================================

model = CNNModel().to(device)

print(model)

"""Training Function"""

# ==========================================================
# Training Function
# ==========================================================

def train_model(model, train_loader, val_loader, optimizer, epochs=10):

    criterion = nn.CrossEntropyLoss()

    train_losses = []
    val_losses = []

    train_accuracies = []
    val_accuracies = []

    for epoch in range(epochs):

        # ==================================================
        # Training Phase
        # ==================================================

        model.train()

        running_loss = 0.0
        correct = 0
        total = 0

        for images, labels in train_loader:

            images = images.to(device)
            labels = labels.to(device)

            # Clear gradients
            optimizer.zero_grad()

            # Forward pass
            outputs = model(images)

            # Calculate loss
            loss = criterion(outputs, labels)

            # Backpropagation
            loss.backward()

            # Update weights
            optimizer.step()

            running_loss += loss.item()

            # Predictions
            _, predicted = torch.max(outputs.data, 1)

            total += labels.size(0)

            correct += (predicted == labels).sum().item()

        train_loss = running_loss / len(train_loader)

        train_accuracy = 100 * correct / total

        train_losses.append(train_loss)
        train_accuracies.append(train_accuracy)

        # ==================================================
        # Validation Phase
        # ==================================================

        model.eval()

        val_loss = 0.0
        correct = 0
        total = 0

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)

                loss = criterion(outputs, labels)

                val_loss += loss.item()

                _, predicted = torch.max(outputs.data, 1)

                total += labels.size(0)

                correct += (predicted == labels).sum().item()

        val_loss = val_loss / len(val_loader)

        val_accuracy = 100 * correct / total

        val_losses.append(val_loss)
        val_accuracies.append(val_accuracy)

        # ==================================================
        # Print Epoch Results
        # ==================================================

        print(f"Epoch [{epoch+1}/{epochs}]")

        print(f"Train Loss: {train_loss:.4f}")

        print(f"Train Accuracy: {train_accuracy:.2f}%")

        print(f"Validation Loss: {val_loss:.4f}")

        print(f"Validation Accuracy: {val_accuracy:.2f}%")

        print("-" * 50)

    return train_losses, val_losses, train_accuracies, val_accuracies

"""Experiment 1

Optimizer: Adam

Batch Size: 64
"""

# ==========================================================
# Create DataLoaders for Experiment 1
# ==========================================================

train_loader_1 = DataLoader(
    train_data,
    batch_size=64,
    shuffle=True
)

val_loader_1 = DataLoader(
    val_data,
    batch_size=64,
    shuffle=False
)

test_loader_1 = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False
)

# ==========================================================
# Initialize Model
# ==========================================================

model_adam = CNNModel().to(device)

# Adam Optimizer
optimizer_adam = optim.Adam(model_adam.parameters(), lr=0.001)

# ==========================================================
# Train Model
# ==========================================================

adam_results = train_model(
    model_adam,
    train_loader_1,
    val_loader_1,
    optimizer_adam,
    epochs=10
)

"""Experiment 2

Optimizer: SGD

Batch Size: 128
"""

# ==========================================================
# Create DataLoaders for Experiment 2
# ==========================================================

train_loader_2 = DataLoader(
    train_data,
    batch_size=128,
    shuffle=True
)

val_loader_2 = DataLoader(
    val_data,
    batch_size=128,
    shuffle=False
)

test_loader_2 = DataLoader(
    test_dataset,
    batch_size=128,
    shuffle=False
)

# ==========================================================
# Initialize Model
# ==========================================================

model_sgd = CNNModel().to(device)

# SGD Optimizer
optimizer_sgd = optim.SGD(model_sgd.parameters(), lr=0.01)

# ==========================================================
# Train Model
# ==========================================================

sgd_results = train_model(
    model_sgd,
    train_loader_2,
    val_loader_2,
    optimizer_sgd,
    epochs=10
)

"""Evaluation Function"""

# ==========================================================
# Evaluation Function
# ==========================================================

def evaluate_model(model, test_loader):

    criterion = nn.CrossEntropyLoss()

    model.eval()

    test_loss = 0.0

    correct = 0
    total = 0

    all_labels = []
    all_predictions = []

    with torch.no_grad():

        for images, labels in test_loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            test_loss += loss.item()

            _, predicted = torch.max(outputs.data, 1)

            total += labels.size(0)

            correct += (predicted == labels).sum().item()

            all_labels.extend(labels.cpu().numpy())

            all_predictions.extend(predicted.cpu().numpy())

    avg_loss = test_loss / len(test_loader)

    accuracy = 100 * correct / total

    return avg_loss, accuracy, all_labels, all_predictions

"""Evaluate Experiment 1"""

# ==========================================================
# Evaluate Adam Model
# ==========================================================

adam_loss, adam_accuracy, adam_labels, adam_predictions = evaluate_model(
    model_adam,
    test_loader_1
)

print("Experiment 1 - Adam Optimizer")

print(f"Test Loss: {adam_loss:.4f}")

print(f"Test Accuracy: {adam_accuracy:.2f}%")

"""Evaluate Experiment 2"""

# ==========================================================
# Evaluate SGD Model
# ==========================================================

sgd_loss, sgd_accuracy, sgd_labels, sgd_predictions = evaluate_model(
    model_sgd,
    test_loader_2
)

print("Experiment 2 - SGD Optimizer")

print(f"Test Loss: {sgd_loss:.4f}")

print(f"Test Accuracy: {sgd_accuracy:.2f}%")

"""Results Comparison Table"""

# ==========================================================
# Create Results DataFrame
# ==========================================================

results_df = pd.DataFrame({

    "Model": ["Model A", "Model B"],

    "Optimizer": ["Adam", "SGD"],

    "Batch Size": [64, 128],

    "Accuracy": [adam_accuracy, sgd_accuracy],

    "Loss": [adam_loss, sgd_loss]
})

results_df

"""Accuracy Curves"""

# ==========================================================
# Plot Accuracy Curves
# ==========================================================

adam_train_losses, adam_val_losses, adam_train_acc, adam_val_acc = adam_results

sgd_train_losses, sgd_val_losses, sgd_train_acc, sgd_val_acc = sgd_results

plt.figure(figsize=(12,5))

plt.plot(adam_train_acc, label='Adam Training Accuracy')

plt.plot(adam_val_acc, label='Adam Validation Accuracy')

plt.plot(sgd_train_acc, label='SGD Training Accuracy')

plt.plot(sgd_val_acc, label='SGD Validation Accuracy')

plt.title("Training vs Validation Accuracy")

plt.xlabel("Epoch")

plt.ylabel("Accuracy (%)")

plt.legend()

plt.grid(True)

plt.show()

"""Loss Curves"""

# ==========================================================
# Plot Loss Curves
# ==========================================================

plt.figure(figsize=(12,5))

plt.plot(adam_train_losses, label='Adam Training Loss')

plt.plot(adam_val_losses, label='Adam Validation Loss')

plt.plot(sgd_train_losses, label='SGD Training Loss')

plt.plot(sgd_val_losses, label='SGD Validation Loss')

plt.title("Training vs Validation Loss")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.legend()

plt.grid(True)

plt.show()

"""Classification Report"""

# ==========================================================
# Classification Report for Adam Model
# ==========================================================

print("Classification Report:\n")

print(classification_report(adam_labels, adam_predictions))

"""Confusion Matrix"""

# ==========================================================
# Confusion Matrix
# ==========================================================

cm = confusion_matrix(adam_labels, adam_predictions)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")

plt.xlabel("Predicted Label")

plt.ylabel("True Label")

plt.show()

"""Sample Predictions Visualization"""

# ==========================================================
# Visualize Random Predictions
# ==========================================================

examples = iter(test_loader_1)

example_images, example_labels = next(examples)

example_images = example_images.to(device)

outputs = model_adam(example_images)

_, predictions = torch.max(outputs, 1)

example_images = example_images.cpu()

plt.figure(figsize=(15,8))

for i in range(15):

    plt.subplot(3,5,i+1)

    image = example_images[i].squeeze()

    plt.imshow(image, cmap='gray')

    plt.title(
        f"True: {example_labels[i]}\nPred: {predictions[i].item()}"
    )

    plt.axis('off')

plt.tight_layout()

plt.show()

"""Save Trained Model"""

# ==========================================================
# Save Model
# ==========================================================

torch.save(model_adam.state_dict(), "mnist_cnn_pytorch.pth")

print("Model saved successfully!")

"""Load Saved Model"""

# ==========================================================
# Load Saved Model
# ==========================================================

loaded_model = CNNModel().to(device)

loaded_model.load_state_dict(
    torch.load("mnist_cnn_pytorch.pth")
)

loaded_model.eval()

print("Model loaded successfully!")

"""Optimizer Comparison Discussion"""

# ==========================================================
# Discussion
# ==========================================================

print("Experiment Comparison:\n")

print("1. Adam Optimizer:")
print("- Faster convergence")
print("- Higher accuracy")
print("- Adaptive learning rate")

print("\n2. SGD Optimizer:")
print("- Slower convergence")
print("- Simpler optimization approach")
print("- Requires more tuning")

print("\nConclusion:")
print("Adam generally performs better on MNIST because")
print("it adapts learning rates automatically and")
print("converges faster than SGD.")